import styles from './layout.module.css'
import './global.css'
import QueryProvider from '@/shared/utils/QueryProvider';
import { AuthRootProvider } from '@/shared/utils/AuthProvider';
import { Layout } from '@/shared/components/Layout';
import ClientToast from '@/shared/components/ClientToast';

export const metadata = {
  title: "SSSP",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Press+Start+2P&family=Share+Tech+Mono&family=VT323&family=Silkscreen&display=swap"
          rel="stylesheet"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={styles.root}>
        <AuthRootProvider>
          <QueryProvider>
            <Layout>
              {children}
            </Layout>
          </QueryProvider>
        </AuthRootProvider>
        <ClientToast />
      </body>
    </html>
  );
}
