import { Query } from "@tanstack/react-query";
import "./global.css";
import QueryProvider from "@/shared/utils/QueryProvider";

export const metadata = {
  title: "SSSP",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
